wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    code_path: code/metrics/xception/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.10
    start_time: 1638477869
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.10
      5: 0.12.1
      8:
      - 2
      - 5
